name: GCR-Test
on:
  push:

jobs:

  startup:
    runs-on: ubuntu-20.04
    steps:

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 312.0.0
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Setup software we'll need
        run: sudo apt install -y ca-certificates curl netcat

      - name: Test Google Cloud SDK
        run: |
          gcloud compute start-iap-tunnel sheep-dog 15000 --local-host-port localhost:6444 &
          sh -c 'until nc -z localhost 6444 ; do sleep 1 ; done ; curl http://localhost:6444 '

