name: GCR-Test
on:
  push:

jobs:
  startup:
    runs-on: google/cloud-sdk:355.0.0-alpine
    steps:
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 312.0.0
      - name: Test Google Cloud SDK
        run: gcloud version

