# IMPORTANT!!!
#
# This workflow requires the "WG_PRIVATE_KEY" secret to be present. This
# will be the private key used when we run in a container.

name: Wireguard-Tunnel
on:
  push:
    branches:
      - "wg-*"

jobs:

  startup:
    runs-on: ubuntu-20.04

    steps:

      - name: install wireguard software
        run: |
          sudo apt-get update
          sudo apt-get -y install wireguard

      - name: setup wireguard
        env:
          CFG: "/etc/wireguard/wg0.conf"
          MY_KEY: "/etc/wireguard/key.private"
          SVR_PUB: "6+Wmt0y4izSh48Vu9PjK1IH3MmiuiB34RY/0n1TtqkY="
        run: |
          sudo bash -c "
            echo '${{ secrets.WG_PRIVATE_KEY }}'                >$MY_KEY
            chmod 400 $MY_KEY
            echo '[Interface]'                                  >$CFG
            echo 'Address = 192.168.4.135/32'                   >>$CFG
            echo 'ListenPort = 51822'                           >>$CFG
            echo \"PostUp = wg set %i private-key $MY_KEY\"     >>$CFG
            echo '[Peer]'                                       >>$CFG
            echo \"PublicKey = $SVR_PUB\"                       >>$CFG
            echo 'EndPoint = 174.89.145.130:51821'              >>$CFG
            echo 'AllowedIPs = 192.168.0.0/16'                  >>$CFG
            ls -la /etc/wireguard
            cat /etc/wireguard/wg0.conf
            wg-quick up wg0
            wg show
            ping -c 5 192.168.3.1
          "


